import { Lot, HerRating } from './types'

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().split('T')[0]
}

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString().split('T')[0]
}

export const LOCATIONS = [
  'Main Warehouse',
  'Southside Pantry',
  'Eastside Community Center',
  'Doney Park Outreach',
] as const

export const LOCATION_DEMAND: {
  location: string
  weeklyDemandLbs: number
  populationServed: number
}[] = [
  { location: 'Main Warehouse', weeklyDemandLbs: 8000, populationServed: 0 },
  { location: 'Southside Pantry', weeklyDemandLbs: 4500, populationServed: 2800 },
  { location: 'Eastside Community Center', weeklyDemandLbs: 3200, populationServed: 1600 },
  { location: 'Doney Park Outreach', weeklyDemandLbs: 2000, populationServed: 950 },
]

export const INITIAL_LOTS: Lot[] = [
  // ── CRITICAL (≤3 days) — the demo tension ──────────────────────
  {
    lotId: 'LOT-001',
    itemName: 'Whole Milk (Gallons)',
    category: 'dairy',
    quantity: 1200,
    unit: 'lbs',
    expirationDate: daysFromNow(2),
    receivedDate: daysAgo(3),
    location: 'Main Warehouse',
    condition: 'near-expiry',
    source: "Fry's Food (Kroger)",
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-002',
    itemName: 'Fresh Apples (Gala)',
    category: 'produce',
    quantity: 1500,
    unit: 'lbs',
    expirationDate: daysFromNow(3),
    receivedDate: daysAgo(4),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'Flagstaff Community Gardens',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-003',
    itemName: 'Artisan Bread Loaves',
    category: 'bakery',
    quantity: 600,
    unit: 'lbs',
    expirationDate: daysFromNow(1),
    receivedDate: daysAgo(1),
    location: 'Southside Pantry',
    condition: 'near-expiry',
    source: 'Macy\'s European Coffeehouse',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-004',
    itemName: 'Greek Yogurt (Cases)',
    category: 'dairy',
    quantity: 200,
    unit: 'lbs',
    expirationDate: daysFromNow(2),
    receivedDate: daysAgo(4),
    location: 'Southside Pantry',
    condition: 'good',
    source: 'Walmart Supercenter',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-005',
    itemName: 'Ground Beef (80/20)',
    category: 'protein',
    quantity: 400,
    unit: 'lbs',
    expirationDate: daysFromNow(2),
    receivedDate: daysAgo(2),
    location: 'Main Warehouse',
    condition: 'near-expiry',
    source: "Bashas' Grocery",
    herRating: 'yellow' as HerRating,
  },

  // ── WARNING (4-7 days) ─────────────────────────────────────────
  {
    lotId: 'LOT-006',
    itemName: 'Whole Milk (Half Gallons)',
    category: 'dairy',
    quantity: 800,
    unit: 'lbs',
    expirationDate: daysFromNow(5),
    receivedDate: daysAgo(2),
    location: 'Main Warehouse',
    condition: 'good',
    source: "Fry's Food (Kroger)",
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-007',
    itemName: 'Orange Juice (Cartons)',
    category: 'produce',
    quantity: 250,
    unit: 'lbs',
    expirationDate: daysFromNow(6),
    receivedDate: daysAgo(2),
    location: 'Southside Pantry',
    condition: 'good',
    source: 'United Way of Northern AZ',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-008',
    itemName: 'Ground Turkey',
    category: 'protein',
    quantity: 180,
    unit: 'lbs',
    expirationDate: daysFromNow(4),
    receivedDate: daysAgo(3),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'Sysco Food Services',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-009',
    itemName: 'Fresh Carrots (Bulk)',
    category: 'produce',
    quantity: 350,
    unit: 'lbs',
    expirationDate: daysFromNow(5),
    receivedDate: daysAgo(3),
    location: 'Eastside Community Center',
    condition: 'good',
    source: 'Flagstaff Community Gardens',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-010',
    itemName: 'Dinner Rolls (Bags)',
    category: 'bakery',
    quantity: 120,
    unit: 'lbs',
    expirationDate: daysFromNow(4),
    receivedDate: daysAgo(2),
    location: 'Eastside Community Center',
    condition: 'good',
    source: 'NAU Food Rescue',
    herRating: 'yellow' as HerRating,
  },

  // ── SAFE (>7 days) — stable foundation ─────────────────────────
  {
    lotId: 'LOT-011',
    itemName: 'Canned Black Beans',
    category: 'canned',
    quantity: 3000,
    unit: 'lbs',
    expirationDate: daysFromNow(250),
    receivedDate: daysAgo(15),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'USDA TEFAP',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-012',
    itemName: 'Frozen Chicken Thighs',
    category: 'frozen',
    quantity: 900,
    unit: 'lbs',
    expirationDate: daysFromNow(35),
    receivedDate: daysAgo(10),
    location: 'Eastside Community Center',
    condition: 'good',
    source: 'Perdue Farms',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-013',
    itemName: 'Peanut Butter (Jars)',
    category: 'protein',
    quantity: 350,
    unit: 'lbs',
    expirationDate: daysFromNow(240),
    receivedDate: daysAgo(10),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'Coconino County Food Drive',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-014',
    itemName: 'Canned Diced Tomatoes',
    category: 'canned',
    quantity: 500,
    unit: 'lbs',
    expirationDate: daysFromNow(180),
    receivedDate: daysAgo(14),
    location: 'Southside Pantry',
    condition: 'good',
    source: "Hunt's Factory Direct",
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-015',
    itemName: 'White Rice (50lb Bags)',
    category: 'grains',
    quantity: 600,
    unit: 'lbs',
    expirationDate: daysFromNow(365),
    receivedDate: daysAgo(30),
    location: 'Doney Park Outreach',
    condition: 'good',
    source: 'USDA TEFAP',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-016',
    itemName: 'Whole Wheat Pasta',
    category: 'grains',
    quantity: 450,
    unit: 'lbs',
    expirationDate: daysFromNow(200),
    receivedDate: daysAgo(20),
    location: 'Main Warehouse',
    condition: 'good',
    source: "Bashas' Grocery",
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-017',
    itemName: 'Frozen Mixed Vegetables',
    category: 'frozen',
    quantity: 700,
    unit: 'lbs',
    expirationDate: daysFromNow(45),
    receivedDate: daysAgo(5),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'Sysco Food Services',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-018',
    itemName: 'Eggs (Dozen Cartons)',
    category: 'protein',
    quantity: 280,
    unit: 'lbs',
    expirationDate: daysFromNow(14),
    receivedDate: daysAgo(3),
    location: 'Southside Pantry',
    condition: 'good',
    source: 'Hickman\'s Family Farms',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-019',
    itemName: 'Canned Corn',
    category: 'canned',
    quantity: 400,
    unit: 'lbs',
    expirationDate: daysFromNow(300),
    receivedDate: daysAgo(12),
    location: 'Doney Park Outreach',
    condition: 'good',
    source: 'USDA TEFAP',
    herRating: 'green' as HerRating,
  },
  {
    lotId: 'LOT-020',
    itemName: 'Breakfast Cereal (Boxes)',
    category: 'grains',
    quantity: 320,
    unit: 'lbs',
    expirationDate: daysFromNow(120),
    receivedDate: daysAgo(7),
    location: 'Eastside Community Center',
    condition: 'good',
    source: 'NAU Food Rescue',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-021',
    itemName: 'Cheddar Cheese (Blocks)',
    category: 'dairy',
    quantity: 260,
    unit: 'lbs',
    expirationDate: daysFromNow(21),
    receivedDate: daysAgo(5),
    location: 'Main Warehouse',
    condition: 'good',
    source: 'Walmart Supercenter',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-022',
    itemName: 'Canned Chicken Soup',
    category: 'canned',
    quantity: 550,
    unit: 'lbs',
    expirationDate: daysFromNow(400),
    receivedDate: daysAgo(8),
    location: 'Southside Pantry',
    condition: 'good',
    source: 'Coconino County Food Drive',
    herRating: 'yellow' as HerRating,
  },
  {
    lotId: 'LOT-023',
    itemName: 'Frozen Burritos',
    category: 'frozen',
    quantity: 340,
    unit: 'lbs',
    expirationDate: daysFromNow(60),
    receivedDate: daysAgo(6),
    location: 'Doney Park Outreach',
    condition: 'good',
    source: 'El Monterey Donation',
    herRating: 'red' as HerRating,
  },
  {
    lotId: 'LOT-024',
    itemName: 'Romaine Lettuce',
    category: 'produce',
    quantity: 180,
    unit: 'lbs',
    expirationDate: daysFromNow(5),
    receivedDate: daysAgo(1),
    location: 'Eastside Community Center',
    condition: 'good',
    source: 'Flagstaff Community Gardens',
    herRating: 'green' as HerRating,
  },
]
